version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build-and-scan:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run build
          command: CI=false npm run build
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-scan:
          context: SonarCloud
